### ISSUE TITLE
Client Secret Error

### ISSUE THREAD

**Issue by dongheechoi** [Azure-Samples/active-directory-java-native-headless#1]
I got a client secret error while running this.
I want to add client_secret, but there's no clues in README.md. 
Below are a full stacktrace of this problem.

Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: xxxxx\r\nCorrelation ID: xxxxx\r\nTimestamp: 2016-05-03 12:22:12Z","error":"invalid_request"}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:41)
    at PublicClient.main(PublicClient.java:25)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: xxxxx\r\nCorrelation ID: xxxxx\r\nTimestamp: 2016-05-03 12:22:12Z","error":"invalid_request"}
    at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:107)
    at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:818)
    at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:66)
    at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:174)
    at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:163)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by gabrielbratescu** [comment]
I am having the same issue. Any help ?

**Comment by gabrielbratescu** [comment]
It seems that other had this problem too.
In Azure the app must be 'native client app' instead of 'web app'
See: https://github.com/Azure-Samples/active-directory-dotnet-graphapi-console/issues/4

**Comment by brandwe** [comment]
I'll take a look at this today.

**Comment by yogesh-nerkar-mpf** [comment]
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID 'a5fb843e-eca2-485f-b335-89f04bc673b4'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 476ebe28-a8ec-4328-8b49-ecd8ca008970\r\nCorrelation ID: 08927192-9fc9-49b2-b75a-c295f809db60\r\nTimestamp: 2016-10-03 07:48:18Z","error":"invalid_grant"}

**Comment by yogesh-nerkar-mpf** [comment]
I am getting above exception while using "Native" app.

**Comment by yogesh-nerkar-mpf** [comment]
@brandwe 

Please look into this. thanks

**Comment by brandwe** [comment]
@yogeshne You don't have interactive capability in Java to consent. You should use client credentials flow. Look here: https://azure.microsoft.com/en-us/documentation/articles/active-directory-protocols-oauth-service-to-service/

**Comment by dominik42** [comment]
I've got the same error mentioned above ```error_description":"AADSTS65001: The user or administrator has not consented to use the application with <AppId>```. I've solved this problem by grant permission to the app via <azure portal> / MyApp / Settings / Required Permission / Grant Permission (item to the right of "+Add").

**Comment by jmprieur** [comment]
Thanks for your feedback. The sample has now be updated with clear instructions in the Readme.md on how to register the Azure AD application (or even scripts to do that)

**Comment by roopam94** [comment]
Hi All, Can anyone suggest me the way to select the "Native Client App" instead of "Web App", I mean where do i change this setting because i am also getting the same error.

**Comment by roopam94** [comment]
> I've got the same error mentioned above `error_description":"AADSTS65001: The user or administrator has not consented to use the application with <AppId>`. I've solved this problem by grant permission to the app via / MyApp / Settings / Required Permission / Grant Permission (item to the right of "+Add").

Can you suggest me the way to do this in my project?

**Comment by repo-gsr** [comment]
@dominik42
can you please provide clear steps where we need to add the Required Permission.
am looking in to this issue many days on words but am not getting right solution. if you provide steps to add permission it will save my time.

**Log trace:** 
java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID 'c980ce84-7d4a-445f-894d-9113a9ffd533' named 'SpringBootApiNativeClient'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 063f0320-d0d8-4fe2-910d-e5e3466a6500\r\nCorrelation ID: e5cab8c1-3744-4bea-970b-ea801ad7a775\r\nTimestamp: 2019-08-04 03:57:39Z","error":"invalid_grant"}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.act.AzureAccessToken.main(AzureAccessToken.java:36)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID 'c980ce84-7d4a-445f-894d-9113a9ffd533' named 'SpringBootApiNativeClient'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 063f0320-d0d8-4fe2-910d-e5e3466a6500\r\nCorrelation ID: e5cab8c1-3744-4bea-970b-ea801ad7a775\r\nTimestamp: 2019-08-04 03:57:39Z","error":"invalid_grant"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:129)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by repo-gsr** [comment]
Thanks Its Working.

**Comment by repo-gsr** [comment]
Can we Create one Native Application for both Client App and Web Api. Insted of maintaining Client as Native and Web Api as Web App in Azure?

**Comment by jmprieur** [comment]
@repo-gsr : Indeed, with the Microsoft identity platform (formerly Azure AD v2.0), you can create an application which supports several platforms / scenarios, for instance indeed native apps, and Web API. The same client ID can be used in both.
