### ISSUE TITLE
AuthenticationException: WsTrust endpoint not found

### ISSUE THREAD

**Issue by padmalava** [Azure-Samples/active-directory-java-native-headless#13]
Hi All,
I am getting a "WsTrust endpoint Not Found" exception. Please help.
Thanks in advance.

com.microsoft.aad.adal4j.AuthenticationException: WsTrust endpoint not found in metadata document
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:50)
        at PublicClient.main(PublicClient.java:31)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: WsTrust endpoint not found in metadata document
        at com.microsoft.aad.adal4j.WSTrustRequest.execute(WSTrustRequest.java:87)
        at com.microsoft.aad.adal4j.AuthenticationContext.processPasswordGrant(AuthenticationContext.java:990)
        at com.microsoft.aad.adal4j.AuthenticationContext.access$000(AuthenticationContext.java:69)
        at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:178)
        at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:168)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by apraovjr** [comment]
@padmalava same here

**Comment by bikramadityauipath** [comment]
Am also getting this error. Were you able to resolve it? @padmalava

**Comment by sangonzal** [comment]
@bikramadityauipath Did you create an AD tenant and are you using one of the users registered in that tenant to log in? Instructions on how to create your own tenant - https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-create-new-tenant

**Comment by sangonzal** [comment]
If you followed those intructions, when you click on "Azure Active Directory" on the menu in the left hand side, click on "All users", then click on the user, you should see something like this: Note the highlighted parts 
![ad](https://user-images.githubusercontent.com/35743865/52001864-4fcb2e00-2475-11e9-8784-959b19ee89c7.png)

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/ms-identity-java-desktop/tree/master/Username-Password-Flow
