### ISSUE TITLE
AADSTS90013: Invalid input received from the user

### ISSUE THREAD

**Issue by TTPBruce** [Azure-Samples/active-directory-java-native-headless#15]
I followed the quick start instructions but I'm getting the following error. Any help?

```
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS90013: Invalid input received from the user.\r\nTrace ID: <ID-HERE>\r\nCorrelation ID: <ID-HERE>\r\nTimestamp: 2018-10-10 16:53:55Z","error":"invalid_request"}
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:56)
        at PublicClient.main(PublicClient.java:30)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS90013: Invalid input received from the user.\r\nTrace ID: <ID-HERE>\r\nCorrelation ID: <ID-HERE>\r\nTimestamp: 2018-10-10 16:53:55Z","error":"invalid_request"}
        at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:120)
        at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:968)
        at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:69)
        at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:179)
        at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:168)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by TTPBruce** [comment]
I believe this has to do with special characters in the password. The user I was trying with had "<" in the password. Tried with another user and was able to authenticate.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/ms-identity-java-desktop/tree/master/Username-Password-Flow
