### ISSUE TITLE
Issue with 'client_secret or client_assertion' missing

### ISSUE THREAD

**Issue by AnandSoniMize** [Azure-Samples/active-directory-java-native-headless#17]
When i try to run, it ask for client secret value and i don't see any place holder to pass it. **How should i change it from Native to Web App inorder to work with it?**

com.microsoft.aad.adal4j.AuthenticationException: {*"error_description":"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: ddaafa2d-fb07-40f2-a1e6-34bc5de64d00\r\nCorrelation ID: ebc9046c-afdb-44e1-be41-69c4e55988a3\r\nTimestamp: 2018-11-16 14:12:53Z","error":"invalid_client"}*
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: ddaafa2d-fb07-40f2-a1e6-34bc5de64d00\r\nCorrelation ID: ebc9046c-afdb-44e1-be41-69c4e55988a3\r\nTimestamp: 2018-11-16 14:12:53Z","error":"invalid_client"}
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.mize.sharepoint.test.TestSharePointConnection.getAccessTokenFromUserCredentials(TestSharePointConnection.java:55)
	at com.mize.sharepoint.test.TestSharePointConnection.main(TestSharePointConnection.java:33)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: ddaafa2d-fb07-40f2-a1e6-34bc5de64d00\r\nCorrelation ID: ebc9046c-afdb-44e1-be41-69c4e55988a3\r\nTimestamp: 2018-11-16 14:12:53Z","error":"invalid_client"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:128)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by sangonzal** [comment]
@AnandSoniMize  to acquire tokens for a web app, you should be using one of the confidential client APIs. Take a look at the [ADAL Java Wiki](https://github.com/AzureAD/azure-activedirectory-library-for-java/wiki/Acquire-tokens), which explains the differences in between the public client and confidential client APIs, and how to use them.
