### ISSUE TITLE
Getting error regarding usage of application was not consented

### ISSUE THREAD

**Issue by olra0001** [Azure-Samples/active-directory-java-native-headless#2]
When following the instructions provided in the README I'm getting the following exception:

```
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID '<MyAppID>'. Send an interactive authorization request for this user and resource.\r\nTrace ID: ----
\r\nCorrelation ID: ----\r\nTimestamp: 2016-10-29 15:11:55Z","error":"invalid_grant"}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at PublicClient.getAccessTokenFromUserCredentials(PublicClient.java:49)
    at PublicClient.main(PublicClient.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID <MyAppID>. Send an interactive authorization request for this user and resource.\r\nTrace ID: ----\r\nCorrelation ID: ----\r\nTimestamp: 2016-10-29 15:11:55Z","error":"invalid_grant"}
    at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:107)
    at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:818)
    at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:66)
    at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:174)
    at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:163)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

When I create the Application within the legacy Azure UI (http://manage.windowsazure.com) it is working. When reviewing that application within the new Azure Portal I see that it is also listed as a Enterprise App as well as showing as "Managed Application In Local Directory" when viewing the App Registration

Note that the exception was also mentioned in Issue #1, but #1 focusses on a different issue.

**Comment by jmprieur** [comment]
Thanks for your feedback. The sample has now be updated with clear instructions in the Readme.md on how to register the Azure AD application (or even scripts to do that), and how to run it
